language: perl
perl:
# - "5.22"
# - "5.18"
  - "5.10"

services:
    - mysql

addons:
  apt:
    packages:
    - expat
    - gettext
    - apache2
    - apache2.2-common
    - apache2-mpm-worker
    - libapache2-mod-perl2
    - libapache2-mod-perl2-dev
    - libdigest-hmac-perl
    - libssl-dev
    - bind9utils
    - librpc-xml-perl
    - libxml-libxml-perl
    - libapache-dbi-perl
    - libxml-parser-perl
    - libjson-perl
    - libsoap-lite-perl
    - libmodule-build-perl
    - libmime-base32-perl
    - libmime-base64-perl
    - libbind-confparser-perl
    - libcrypt-openssl-rsa-perl
    - libcrypt-openssl-dsa-perl
    - libyaml-perl
    - libwww-perl
    - liburi-perl
    - libmime-tools-perl
    - libmailtools-perl
    - libfile-sharedir-perl
    - libperl-prereqscanner-perl
    - libdbix-simple-perl
    - libdbi-perl
    - libnet-ip-perl
    - libnet-dns-perl

before_install:
    - sudo .test/tls-setup.sh
    # - sudo apt-get install libextutils-makemaker-perl || echo "nope"
    # - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
      # globally/system installed perl modules
    - cpanm --notest CGI RPC::XML Time::TAI64 CryptX Crypt::Mac::HMAC Crypt::KeyDerivation DBD::mysql Test::HTML::Lint Apache::DBI Shell LWP::UserAgent Test::Output Test::Pod MIME::Base32
    - cpanm --notest --force Net::DNS || sudo cpanm --notest --force Net::DNS@1.0.6 || echo "double darn"
    - cpanm --notest JSON SOAP::Lite XML::Parser Net::DNS Net::IP BIND::Conf_Parser DBIx::Simple DBI

install:
    - sudo cp .test/apache-nictool.conf /etc/apache2/sites-enabled/
    - sudo service apache2 restart || sudo cat /var/log/apache2/error.log
    - perl .test/create_tables.pl

before_script:

script:
    - cd /home/travis/build/msimerson/NicTool/client && perl Makefile.PL
    - make -C /home/travis/build/msimerson/NicTool/client test
    - cd /home/travis/build/msimerson/NicTool/server && perl Makefile.PL
    - make -C /home/travis/build/msimerson/NicTool/server test

after_success:
after_failure:
    - pwd
    - cat /var/log/apache2/error.log
    - cat /etc/apache2/apache2.conf
    - ls /usr/lib/apache2/modules/
after_script:

#sudo: false
